
on: [pull_request]
name: test
jobs:
  test:
    name: ${{ matrix.config.target }} (${{ matrix.profile.name }})
    runs-on: ${{ matrix.config.os }}-latest
    steps:
      - run: ${{ matrix.config.prep }}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.config.target }}
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.profile.flag }} --target=${{ matrix.config.target }}
    strategy:
      fail-fast: false
      matrix:
        profile:
          - name: debug
          - name: release
            flag: --release
        config:
          - target: i586-pc-windows-msvc
            os: windows
          - target: i586-unknown-linux-gnu
            prep: sudo apt install -y gcc-multilib
            os: ubuntu
          - target: i586-unknown-linux-musl
            os: ubuntu
          - target: i686-pc-windows-msvc
            os: windows
          - target: i686-unknown-linux-gnu
            prep: sudo apt install -y gcc-multilib
            os: ubuntu
          - target: i686-unknown-linux-musl
            os: ubuntu
          - target: x86_64-apple-darwin
            os: macos
          - target: x86_64-pc-windows-gnu
            os: windows
          - target: x86_64-pc-windows-msvc
            os: windows
          - target: x86_64-unknown-linux-gnu
            os: ubuntu
          - target: x86_64-unknown-linux-musl
            os: ubuntu
